package com.example.githubusers.navigation.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import java.nio.charset.StandardCharsets
import java.security.MessageDigest

class DeepLinkRegistryProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val moduleName: String,
) : SymbolProcessor {
    override fun process(resolver: com.google.devtools.ksp.processing.Resolver): List<KSAnnotated> {
        // Find classes annotated with @OwnsDeepLinks
        val ownsDeepLinks = resolver.getSymbolsWithAnnotation(
            "com.example.githubusers.navigation.annotations.OwnsDeepLinks"
        ).filterIsInstance<KSClassDeclaration>().toList()

        if (ownsDeepLinks.isEmpty()) return emptyList()

        val entries = ownsDeepLinks.mapNotNull { cls ->
            val moduleIdArg = cls.annotations.firstOrNull {
                it.shortName.asString() == "OwnsDeepLinks"
            }?.arguments?.firstOrNull()?.value as? String ?: return@mapNotNull null
            moduleIdArg to (cls.qualifiedName?.asString() ?: cls.simpleName.asString())
        }

        // Generate a unique, deterministic suffix for this module's ownership provider class
        val digest = MessageDigest.getInstance("SHA-256")
        val hashInput = (moduleName + entries.joinToString(";") { it.first + ":" + it.second }).toByteArray()
        val suffix = digest.digest(hashInput).take(6).joinToString("") { b -> "%02x".format(b) }
        val providerSimpleName = "GeneratedDeepLinkOwners_" + suffix
        val providerFqcn = "com.example.githubusers.navigation.generated." + providerSimpleName

        // Generate provider class implementing navigation-api interface
        val providerText = buildString {
            appendLine("package com.example.githubusers.navigation.generated")
            appendLine()
            appendLine("/** Generated by navigation-ksp. Do not edit. */")
            appendLine("class " + providerSimpleName + " : DeepLinkOwnersProvider {")
            appendLine("  override fun owners(): Map<String, String> = mapOf(")
            appendLine(entries.joinToString(",\n") { (k, v) -> "    \"$k\" to \"$v\"" })
            appendLine("  )")
            appendLine("}")
        }
        codeGenerator.createNewFile(
            Dependencies(aggregating = true, *ownsDeepLinks.mapNotNull { it.containingFile }.toTypedArray()),
            packageName = "com.example.githubusers.navigation.generated",
            fileName = providerSimpleName,
            extensionName = "kt",
        ).use { out -> out.write(providerText.toByteArray(StandardCharsets.UTF_8)) }

        // Generate META-INF/services entry for ServiceLoader
        val servicePath = "META-INF/services/com.example.githubusers.navigation.generated.DeepLinkOwnersProvider"
        codeGenerator.createNewFile(
            Dependencies(aggregating = true, *ownsDeepLinks.mapNotNull { it.containingFile }.toTypedArray()),
            packageName = "",
            fileName = servicePath,
            extensionName = "",
        ).use { out ->
            out.write((providerFqcn + "\n").toByteArray(StandardCharsets.UTF_8))
        }

        return emptyList()
    }
}

class DeepLinkRegistryProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        val moduleName = environment.options["ksp.module.name"]
            ?: environment.options["ksp.processing.module"]
            ?: environment.options["kotlin.ksp.moduleName"]
            ?: "unknown"
        return DeepLinkRegistryProcessor(environment.codeGenerator, environment.logger, moduleName)
    }
}

