org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:+UseStringDeduplication -XX:ActiveProcessorCount=4
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.enableR8.fullMode=true
android.lifecycleProcessor.incremental=true
kotlin.incremental=true
kotlin.incremental.js=true
kotlin.incremental.usePreciseJavaTracking=true
kotlin.parallel.tasks.in.project=true
kotlin.build.report.enable=false
kotlin.daemon.jvm.options=-Xmx3g
